services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/db.sqlite3
    command: >
      sh -c "python manage.py migrate &&
             gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"

volumes:
  sqlite_data:
